export default {
    USER_GLOBAL_ID: '001',
    STORE_GLOBAL_ID: '002',
    MESSAGE_GLOBAL_ID: '010',
    PRODUCT_GLOBAL_ID: '009',
    SELLPOST_DETAIL_GLOBAL_ID: '011',
    SELLPOST_GLOBAL_ID: '012'
}