export const flag = [
    ['cambodia','+855'],
    ['china','+86'],
    ['france','+33'],
    ['germany','+49'],
    ['hong kong','+852'],
    ['indonesia','+62'],
    ['india','+91'],
    ['italy','+39'],
    ['japan','+81'],
    ['laos','+856'],
    ['malaysia','+60'],
    ['mexico','+52'],
    ['russia','+7'],
    ['singapore','+65'],
    ['south korea','+82'],
    ['taiwan','+886'],
    ['thailand','+66'],
    ['united kingdom','+44'],
    ['united states of america','+1'],
    ['vietname','+84'],
]
